import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,readFile,rm,writeFile,stat} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {startHub,defaultScenario,defaultAssignments} from '../src/hub.mjs';
import {createSim,verifyTrajectory,replayActions} from '../src/sim.mjs';
import {toolList,validateCall} from '../src/schema.mjs';
import {McpClient} from '../tools/mcp-client.mjs';
async function fixture(options,fn){const root=await mkdtemp(join(tmpdir(),'sim-delta-'));let hub;const clients={};try{hub=await startHub({root,...options});for(const [id,file] of Object.entries(hub.connections)){clients[id]=new McpClient(file);await clients[id].initialize();}await fn(hub,clients,root);}finally{for(const c of Object.values(clients))await c.close();if(hub)await hub.close();await rm(root,{recursive:true,force:true});}}
async function replay(run){const bytes=await readFile(join(run,'trajectory.jsonl'),'utf8'),actions=(await readFile(join(run,'actions.jsonl'),'utf8')).trim().split('\n').filter(Boolean).map(JSON.parse),header=verifyTrajectory(bytes).records[0],sim=await replayActions(header,actions);try{assert.equal(sim.trajectory(),bytes);}finally{sim.close();}}
test('N-1: schema and catalogs enforce live-only submission for robot and coordinator',()=>{
 const args={robotId:'amber',round:'1:0'};for(const role of ['robot','coordinator']){assert.ok(!toolList(role).some(t=>t.name==='robot.submit'));assert.throws(()=>validateCall({role,agentId:'script-amber',robotId:'amber'},'robot.submit',args,{live:false}),/live mode/);}
 assert.ok(toolList('robot',{live:true}).some(t=>t.name==='robot.submit'));assert.doesNotThrow(()=>validateCall({role:'robot',agentId:'script-amber',robotId:'amber'},'robot.submit',args,{live:true}));
});
test('N-1: manual submit floods write nothing across resets and leave other participants usable',async()=>{
 await fixture({maxRunBytes:262144},async(hub,c)=>{for(let cycle=0;cycle<2;cycle++){const before=await readFile(join(hub.runDir,'actions.jsonl'));for(let i=0;i<200;i++){await assert.rejects(c.amber.call('robot.submit',{robotId:'amber',round:'1:0'}),/live mode/);if(i%20===0)assert.equal((await c.teal.call('sim.status',{})).stopReason,null);}await assert.rejects(c.coordinator.call('robot.submit',{robotId:'teal',round:'1:0'}),/live mode/);assert.deepEqual(await readFile(join(hub.runDir,'actions.jsonl')),before);assert.equal((await c.coordinator.call('sim.status',{})).tick,0);await c.teal.call('robot.drive',{robotId:'teal',v:.1,w:0,duration:1});await c.coordinator.call('sim.step',{n:1});assert.equal((await c.violet.call('sim.status',{})).tick,1);await replay(hub.runDir);if(cycle===0)await c.coordinator.call('sim.reset',{});}});
});
test('N-1: core submissions share the per-tick mutation quota and the recording budget',async()=>{
 const scenario=defaultScenario(),assignments=defaultAssignments(scenario),who={role:'robot',agentId:'script-amber',robotId:'amber'},args={robotId:'amber',round:'1:0'};
 const manual=await createSim({scenario,assignments});try{assert.throws(()=>manual.invoke(who,'robot.submit',args),/live mode/);assert.deepEqual(manual.actions(),[]);}finally{manual.close();}
 const live=await createSim({scenario,assignments,live:true,maxRunBytes:1048576});try{for(let i=0;i<63;i++)live.invoke(who,'robot.drive',{robotId:'amber',v:0,w:0,duration:1,round:'1:0'});live.invoke(who,'robot.submit',args);const before=live.actions();for(let i=0;i<100;i++)assert.throws(()=>live.invoke(who,'robot.submit',args),/Per-robot command budget/);assert.deepEqual(live.actions(),before);assert.equal(live.status().stopReason,null);live.invoke({role:'robot',agentId:'script-teal',robotId:'teal'},'robot.drive',{robotId:'teal',v:0,w:0,duration:1,round:'1:0'});live.step(1);
  let stopped=false;try{for(let tick=0;tick<100;tick++){for(let i=0;i<64;i++)live.invoke(who,'robot.submit',{robotId:'amber',round:`1:${live.status().tick}`});live.step(1);}}catch(e){assert.equal(e.code,'RUN_BYTE_BUDGET');stopped=true;}assert.ok(stopped);const copy=await replayActions(live.header,live.actions());try{assert.equal(copy.trajectory(),live.trajectory());}finally{copy.close();}
 }finally{live.close();}
});
test('N-1: repeated live submissions cannot advance another robot or exhaust shared storage',async()=>{
 await fixture({live:{},maxRunBytes:4194304},async(hub,c)=>{const round=(await c.coordinator.call('sim.status',{})).live.round;for(let i=0;i<63;i++)await c.amber.call('robot.drive',{robotId:'amber',v:0,w:0,duration:1,round});await c.amber.call('robot.submit',{robotId:'amber',round});const before=await readFile(join(hub.runDir,'actions.jsonl'));for(let i=0;i<100;i++)await assert.rejects(c.amber.call('robot.submit',{robotId:'amber',round}),/already submitted/);assert.deepEqual(await readFile(join(hub.runDir,'actions.jsonl')),before);assert.equal((await c.coordinator.call('sim.status',{})).tick,0);await c.teal.call('robot.submit',{robotId:'teal',round});const final=await c.violet.call('robot.submit',{robotId:'violet',round});assert.equal(final.tick,60);assert.equal(final.stopReason,null);await replay(hub.runDir);});
});
test('N-2r: mixed-case and punctuation robot IDs replay identically in manual and live modes',async()=>{
 for(const ids of [['amber','Bolt','cobalt'],['r_1','r-1','r2']])for(const live of [false,true]){const scenario=defaultScenario();scenario.robots.forEach((r,i)=>r.id=ids[i]);const assignments=defaultAssignments(scenario);await fixture({scenario,assignments,...(live?{live:{stepTicks:1}}:{})},async(hub,c)=>{const token=live?(await c.coordinator.call('sim.status',{})).live.round:undefined;for(const id of ids)await c[id].call('robot.drive',{robotId:id,v:.1,w:0,duration:1,...(live?{round:token}:{})});if(live)for(const id of ids)await c[id].call('robot.submit',{robotId:id,round:token});else await c.coordinator.call('sim.step',{n:1});await replay(hub.runDir);if(live){const actions=(await readFile(join(hub.runDir,'actions.jsonl'),'utf8')).trim().split('\n').map(JSON.parse),audit=(await readFile(join(hub.runDir,'live.jsonl'),'utf8')).trim().split('\n').map(JSON.parse),commit=audit.find(e=>e.kind==='commit'),expected=actions.find(e=>e.name==='sim.step').robotIds;assert.deepEqual(commit.robotIds,expected);assert.deepEqual(commit.submitted,expected);assert.deepEqual((await c.coordinator.call('sim.status',{})).live.activeRobots,expected);}});}
});
test('N-3: signals at the first lock, capability or stdout write clean both launcher roots',async()=>{
 const {spawn}=await import('node:child_process'),{readdir}=await import('node:fs/promises');const failures=[];
 for(const entry of ['src/hub-cli.mjs','tools/live.mjs'])for(const stage of ['lock','capability','stdout'])for(const signal of ['SIGTERM','SIGHUP']){const root=await mkdtemp(join(tmpdir(),'sim-start-signal-'));let child;try{const args=stage==='stdout'?[]:['--import',new URL('./fixtures/signal-during-startup.mjs',import.meta.url).href];args.push(entry,'--root',join(root,'hub'));if(entry.includes('live')){const work=join(root,'work.json');await writeFile(work,JSON.stringify({assignments:defaultAssignments(defaultScenario()).map(a=>({...a,driverLabel:'SCRIPT'}))}));args.push('--work-record',work);}
   child=spawn(process.execPath,args,{env:{...process.env,SIM_TEST_SIGNAL_STAGE:stage,SIM_TEST_SIGNAL:signal},stdio:['ignore','pipe','pipe']});let stderr='';child.stderr.on('data',b=>stderr+=b);child.stdout.on('data',()=>{});if(stage==='stdout')child.stdout.once('data',()=>child.kill(signal));const timeout=setTimeout(()=>child.kill('SIGKILL'),5000);const end=await new Promise(r=>child.on('close',(code,signal)=>r({code,signal})));clearTimeout(timeout);const remaining=(await readdir(join(root,'hub'))).filter(name=>name==='hub.lock'||name.startsWith('connection-'));if(end.code!==0||remaining.length)failures.push({entry,stage,signal,end,remaining,stderr});
  }finally{child?.kill('SIGKILL');await rm(root,{recursive:true,force:true});}}
 assert.deepEqual(failures,[]);
});
test('P-N2: a large valid scene reports the work limit distinctly from an unreachable target',async()=>{
 const {validateScenario}=await import('../src/sim.mjs'),{planPath}=await import('../src/path.mjs');const scenario=defaultScenario();scenario.arena={width:60,depth:60};scenario.robots.forEach((r,i)=>{r.x=-25;r.y=-25+i*2;});scenario.crates=Array.from({length:32},(_,i)=>({id:`load-${i}`,x:-25+(i%8)*2,y:15+Math.floor(i/8)*2,zone:scenario.zones[i%3].id}));scenario.obstacles=Array.from({length:32},(_,i)=>({id:`rack-${i}`,x:-10+(i%8)*5,y:-10+Math.floor(i/8)*5,width:2,depth:2}));validateScenario(scenario);
 const blocked=[...scenario.obstacles,...scenario.crates.map(c=>({...c,width:.6,depth:.6})),...scenario.robots.slice(1).map(r=>({...r,width:.66,depth:.66}))],start={x:-25,y:-25},target={x:25,y:25};const reference=planPath(start,target,scenario,blocked,.36,{bounded:false});assert.deepEqual(reference.at(-1),target);assert.throws(()=>planPath(start,target,scenario,blocked,.36),/work budget exceeded.*nearer waypoint/);assert.deepEqual(planPath(start,{x:-24,y:-24},scenario,blocked,.36),[{x:-24,y:-24}]);
});
test('N-4: frozen v1 free-text headers and assignment actions replay without weakening new-run validation',async()=>{
 const {hash}=await import('../src/sim.mjs'),bytes=await readFile(new URL('./fixtures/v1-free-text-trajectory.jsonl',import.meta.url),'utf8'),journal=await readFile(new URL('./fixtures/v1-free-text-actions.jsonl',import.meta.url),'utf8'),receipt=JSON.parse(await readFile(new URL('./fixtures/v1-free-text.json',import.meta.url),'utf8'));assert.equal(hash(bytes),receipt.trajectorySha256);assert.equal(hash(journal),receipt.actionsSha256);const checked=verifyTrajectory(bytes),header=checked.records[0],copy=await replayActions(header,journal.trim().split('\n').map(JSON.parse));try{assert.equal(copy.trajectory(),bytes);assert.equal(copy.snapshot().robots[0].taskId,'Fleet task #99');}finally{copy.close();}
 await assert.rejects(createSim({scenario:header.scenario,assignments:header.assignments}),/invalid string/);await assert.rejects(createSim({scenario:defaultScenario(),assignments:header.assignments}),/invalid string/);
});
